### ISSUE TITLE
When a `hand-drawn` element is selected via the `Select` curser and it's box is shown, the focus on the element (to move it for example) is triggered only when the curser is directly over the `hand-drawn` shape rather than it's entire box.

### ISSUE THREAD

**Issue by mhosnyessa** [The-Zagy/zagydraw#44]
**To Reproduce**
1. Select hand draw from the top toolbar
2. draw some random shape
3. Now click the `selection tool` from the top tollbar
4. Try to select the shape you've just drawn until a dashed box around it appears
5. now try to move it around, you will notice that it will only work if you percisely aim at the shape itself and not just anywhere inside the dashed box.

**Comment by sandstone991** [comment]
Yes the ability to move selection boxes hasn't been implemented yet. you can open this as a feature request instead.
