### ISSUE TITLE
once you zoomed in/out the text element width is not correct any more

### ISSUE THREAD

**Issue by nagy-nabil** [The-Zagy/zagydraw#9]
**Describe the bug**
we use [measureText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) to calculate text element width while generating it so that we can deal with the text element as rect in selection and so on.
the problem is once you zoom the browser in/out the measurement is not correct.

> Note we didn't work on zoom operation yet so this problem could be postponed until we finish zoom

[https://stackoverflow.com/questions/51390232/fixed-font-size-html-canvas-how-to-make-it-change-while-zooming-in-out]( https://stackoverflow.com/questions/51390232/fixed-font-size-html-canvas-how-to-make-it-change-while-zooming-in-out)

**Comment by sandstone991** [comment]
not relevant since the zoom will be in the virtual canvas
